### ISSUE TITLE
KanBan Review for Ruby Capstone

### ISSUE THREAD

**Issue by enmanuelbayen** [enmanuelbayen/Catalog-of-my-things#5]
# FEATURE

 - Create the Kanban using the template for ruby project
 - Here is the[ link](https://github.com/enmanuelbayen/Catalog-of-my-things/projects/1) for the Kanban
 - For this project we're 3 people @StevenWafeek(Team1 task) @gersonhiggins(Team3 task) and my persona @enmanuelbayen (Team2 task).

**Comment by IngDavidTM** [comment]
## Hi Team 🙋‍♂️, 

Good job so far!
You have done well reaching this point of the milestone 🤝 . But there are some issues that you still need to work on to go to the project but you are almost there!

<img src="https://media2.giphy.com/media/31Q36EHJ7C5ZoIMw79/giphy.gif"/>

## Top highlight 🎯
- The Cards were created ✅ 

## Suggested changes

- [ ] You've done an excellent job in developing the KanBan. However, as per project guidelines, it's necessary for all cards to be allocated to team members. I've noticed that your third team member hasn't yet confirmed the invitation. It's crucial to adhere to this requirement, so please be patient while waiting for their response :+1:.

## Optional suggestions

- [OPTIONAL] I suggest generating additional cards to break down each task into separate components. This approach will make it simpler to manage and address each individual task effectively. This recommendation aims to enhance organization and streamline the task management process :+1:.

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by gemmen29** [comment]
Hi Team, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights 💯 
- Descriptive info ✔️
- Tasks distributed equally ✔️  

![](https://media.giphy.com/media/mCIjCgs3nWQWfJZvPA/giphy-downsized-large.gif)

## Optional suggestions:
- [ ] [OPTIONAL] Kindly split the team tasks into smaller tasks that cover a smaller requirement for better organization of the Kanban board.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
